name: Java Unitary Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build and Test
      run: |
        cd java/ddd
        mvn clean install 
        mvn test
